"""Patient-local Monte Carlo simulation entrypoints."""

from .containment import (
    MC_CONTAINMENT_BIOPSY_OUTPUT_KEYS,
    MC_CONTAINMENT_DISTANCE_MERGE_COLUMNS,
    MC_CONTAINMENT_NN_DISTANCE_COLUMN,
    MC_CONTAINMENT_POINT_CONTAINED_COLUMN,
    MC_STRUCTURE_SPECIFIC_RESULT_KEYS,
    PatientContainmentBiopsyContext,
    PatientContainmentCentroidDistanceResult,
    PatientContainmentDilatedStructureBank,
    PatientContainmentKernelResult,
    PatientContainmentNearestNeighbourResult,
    PatientContainmentOutputs,
    PatientContainmentRelativeStructureInput,
    PatientContainmentStructureInventory,
    calculate_patient_relative_structure_centroid_distances,
    calculate_patient_relative_structure_nearest_neighbour_distances,
    build_mutual_structure_specific_results_template,
    build_patient_containment_dilated_structure_bank,
    build_patient_containment_biopsy_context,
    build_patient_containment_relative_structure_input,
    build_structure_specific_results_template,
    collect_patient_containment_outputs,
    iter_patient_containment_relative_structure_inputs,
    merge_patient_relative_structure_containment_dataframes,
    run_patient_relative_structure_containment_core,
    run_patient_relative_structure_containment_kernel,
)
from .contracts import (
    MCContainmentSimulationConfig,
    MCConvexPatientRunResult,
    MCConvexSimulationConfig,
    MCDoseSimulationConfig,
    MCReferenceKeys,
    MCSimulationRuntimeConfig,
)
from .convex_legacy_adapter import (
    build_single_patient_mc_master_info,
    collect_mc_patient_outputs,
    run_patient_mc_convex_legacy_adapter,
)
from .dose import MC_DOSE_BIOPSY_OUTPUT_KEYS, PatientDoseOutputs, collect_patient_dose_outputs
from .legacy_keys import (
    LegacyMCBiopsyIdentityKeys,
    LegacyMCBiopsyOutputKeys,
    LegacyMCContainmentIntermediateKeys,
    LegacyMCKeyBundle,
    LegacyMCMasterInfoKeys,
    legacy_mc_keys,
)
from .relative_structure_inventory import (
    PatientRelativeStructureInventory,
    RelativeStructureInfo,
    build_patient_relative_structure_inventory,
    resolve_patient_info,
)

__all__ = [
    "MCContainmentSimulationConfig",
    "MCConvexPatientRunResult",
    "MCConvexSimulationConfig",
    "MCDoseSimulationConfig",
    "MC_CONTAINMENT_BIOPSY_OUTPUT_KEYS",
    "MC_CONTAINMENT_DISTANCE_MERGE_COLUMNS",
    "MC_CONTAINMENT_NN_DISTANCE_COLUMN",
    "MC_CONTAINMENT_POINT_CONTAINED_COLUMN",
    "MC_DOSE_BIOPSY_OUTPUT_KEYS",
    "MCReferenceKeys",
    "MC_STRUCTURE_SPECIFIC_RESULT_KEYS",
    "MCSimulationRuntimeConfig",
    "LegacyMCBiopsyIdentityKeys",
    "LegacyMCBiopsyOutputKeys",
    "LegacyMCContainmentIntermediateKeys",
    "LegacyMCKeyBundle",
    "LegacyMCMasterInfoKeys",
    "PatientContainmentBiopsyContext",
    "PatientContainmentCentroidDistanceResult",
    "PatientContainmentDilatedStructureBank",
    "PatientContainmentKernelResult",
    "PatientContainmentNearestNeighbourResult",
    "PatientContainmentOutputs",
    "PatientContainmentRelativeStructureInput",
    "PatientContainmentStructureInventory",
    "PatientDoseOutputs",
    "PatientRelativeStructureInventory",
    "RelativeStructureInfo",
    "calculate_patient_relative_structure_centroid_distances",
    "calculate_patient_relative_structure_nearest_neighbour_distances",
    "build_single_patient_mc_master_info",
    "build_mutual_structure_specific_results_template",
    "build_patient_containment_biopsy_context",
    "build_patient_containment_dilated_structure_bank",
    "build_patient_containment_relative_structure_input",
    "build_patient_relative_structure_inventory",
    "build_structure_specific_results_template",
    "collect_mc_patient_outputs",
    "collect_patient_containment_outputs",
    "collect_patient_dose_outputs",
    "iter_patient_containment_relative_structure_inputs",
    "legacy_mc_keys",
    "merge_patient_relative_structure_containment_dataframes",
    "resolve_patient_info",
    "run_patient_relative_structure_containment_core",
    "run_patient_relative_structure_containment_kernel",
    "run_patient_mc_convex_legacy_adapter",
]
